spring:
    application:
        name: user
    datasource:
        url: jdbc:postgresql://localhost:54321/user
        username: postgres
        password: user123
    jpa:
        hibernate:
            ddl-auto: update
    profiles:
        active: development