spring:
    application:
        name: user
    datasource:
        url: jdbc:postgresql://db:5432/user
        username: postgres
        password: user123
        driver-class-name: org.postgresql.Driver