server:
  port: 9090
  
grpc:
    server:
        port: 7091
spring:
    main:
        allow-bean-definition-overriding: true 
    application:
        name: user
    datasource:
        url: jdbc:postgresql://localhost:54321/user
        username: postgres
        password: user123
    jpa:
        hibernate:
            ddl-auto: update
    profiles:
        active: development
