spring:
    application:
        name: user
    datasource:
        url: jdbc:postgresql://localhost:5432/user
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver